### ISSUE TITLE
[Question] Ubuntu v/s Kali

### ISSUE THREAD

**Issue by CodeMaxx** [InfoSecIITR/tools#1]
Any specific reason for recommending Ubuntu instead of Kali? @jaybosamiya

**Comment by jaybosamiya** [comment]
Well, there are a couple of reasons:

First, by manually installing all your requisite tools onto Ubuntu, rather than having them pre-installed, you'd probably know what you are installing and look into why you are installing it. Kali has a plethora of tools that will forever remain unused (at least by me).

Secondly, Kali, by default, runs as root; and I personally find this to be a very bad idea unless you know exactly what you are doing. This is why I'd recommend Ubuntu first, and if someone knows what they are doing, then they already know the risk/benefit payoffs, and they will be knowledgeable enough to make the right choice.

Nevertheless, here's a nice write-up on the Kali website: http://docs.kali.org/introduction/should-i-use-kali-linux

**Comment by CodeMaxx** [comment]
Damn! Now I want to switch to Ubuntu!

**Comment by DhavalKapil** [comment]
Also, Kali is quite 'unstable' as compared to Ubuntu.

**Comment by CodeMaxx** [comment]
@DhavalKapil Just saying that is not very convincing. I've been using Kali for some time(only for ctfs) and it didn't give me any "stability" problems per se

**Comment by DhavalKapil** [comment]
@CodeMaxx I say that with whatever I've experienced. I used Kali for a month when I was interning as a pentester. I am not trying to convince anyone. It's just my opinion :)

**Comment by captn3m0** [comment]
I've found running Kali in a VM instead a nice alternative solution.
